In [3]:
import sys
import os

# Adds the root directory in the repo to sys.path, so we can import modules as dutoolbox.sub_module...
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [4]:
###################################
# Custom libraries/external files #
###################################

# General dual-unitary functions
import dutoolbox.dualunitary as du

# Integrable gates
import dutoolbox.integrable as du_int

# Random matrices
import dutoolbox.randmatrix as rmt

# Miscellaneous functions
import dutoolbox.utils as du_utils
import dutoolbox.utils.pauli as pauli

# Other libraries
import numpy as np

In [5]:
# Random GUE matrix
print(rmt.GUE_matrix(3))

# Random Bernoulli matrix
print(rmt.bernoulli_matrix(3))

# Random lognormal
print(rmt.lognormal_matrix(3))

[[ 0.73673588+0.j          2.00092143+0.56542795j  1.15609619+1.31124658j]
 [ 2.00092143-0.56542795j  1.11737437+0.j         -0.83305777-0.26857619j]
 [ 1.15609619-1.31124658j -0.83305777+0.26857619j -0.73304897+0.j        ]]
[[0 1 2]
 [1 2 1]
 [2 1 2]]
[[0.71407426 1.98304856 0.7286807 ]
 [1.98304856 1.02135355 0.77409586]
 [0.7286807  0.77409586 1.23879518]]


In [6]:
# Tests for dual-unitarity
Jz = 1/np.sqrt(10)
U = du.dual_unitary_gate_qubit(Jz)
du_utils.is_dual_unitary_tensor(U)

True

In [7]:
# Checks for soliton
U = du.dual_unitary_gate_qubit(Jz, local_perturbation=0)
U = U.reshape(4, 4)

# Left moving
np.linalg.norm(U.conj().T @ np.kron(np.eye(2), pauli.Z) @ U - np.kron(pauli.Z, np.eye(2)))

np.float64(6.297618457644295e-16)

In [8]:
# Controlled phase gate
U_int = du_int.dual_unitary_cphase(np.pi/8)
print(U_int)

[[0.92387953+0.38268343j 0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         1.        +0.j
  0.        +0.j        ]
 [0.        +0.j         1.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.        +0.j
  1.        +0.j        ]]


In [9]:
du_utils.is_dual_unitary_tensor(U_int.reshape(2, 2, 2, 2))

True

In [10]:
# Permutations
du_int.permutator([1, 2, 3, 4, 5])

array([2, 4, 1, 5, 3])